## CI Build Script for tbmd.com.
## Build Results Visible at: https://travis-ci.org/bbergen/tbmd.com

language: php

php:
    - 5.4
    - 5.5
    - 5.6

services:
    - mysql

script:
    - ./meta/build.sh